# Generated by Django 2.1.1 on 2019-02-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181022_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='blog.Entry'),
        ),
    ]
